info:
  contact: {}
paths:
  /users:
    get:
      responses: {}
      summary: get all available users from database
      tags:
      - users
    post:
      description: Post user
      responses: {}
      summary: post user
      tags:
      - users
swagger: "2.0"
